CREATE TABLE admin(
 id INT NOT NULL AUTO_INCREMENT,
 email VARCHAR(200) NOT NULL,
 password VARCHAR(200) NOT NULL,
 first_name VARCHAR(200) NOT NULL,
 last_name VARCHAR(200) NOT NULL,
 role VARCHAR(100) NOT NULL DEFAULT 'admin',
 PRIMARY KEY(id),
 CONSTRAINT admin_unique_email UNIQUE(email)

);